### ISSUE TITLE
Readibility

### ISSUE THREAD

**Issue by ufechner7** [baggepinnen/TrajectoryLimiters.jl#3]
In the README.md, but also in the code when I read it on Github x_dot and x_dot_dot are not displayed correctly. This should be fixed.

**Comment by baggepinnen** [comment]
You might be missing a font, it looks fine here

**Comment by ufechner7** [comment]
Just using Ubuntu (both 22.04 and 24.04) and Firefox. Which OS and browser are you using?

**Comment by ufechner7** [comment]
![image](https://github.com/user-attachments/assets/8da00f0c-38fb-486a-92d4-002a0b6c35a7)

I created a pull request that fixes this issue.

**Comment by baggepinnen** [comment]
![image](https://github.com/user-attachments/assets/0db409d9-19ad-4e31-b2ce-d4309ad397c4)

ubuntu, it also looks fine on my phone, and is readable on juliahub:
![image](https://github.com/user-attachments/assets/db624434-2808-4912-8b40-e00b4f81a1a8)
